kind: Service
apiVersion: v1
metadata:
  name:  server-service 
spec:
  selector:
    app:  server-deployment
  type:   ClusterIP 
  ports:
  - name:  server-service
    port:  80
    targetPort: 4000